<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<title>F-ZERO ONLINE!</title>\n";
echo "<meta charset=\"UTF-8\">\n";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n";
echo "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Lato\">\n";
echo "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\n";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
echo "<style>\n";
echo "body,h1,h2,h3,h4,h5,h6 {font-family: \"Lato\", sans-serif}\n";
echo ".w3-bar,h1,button {font-family: \"Montserrat\", sans-serif}\n";
echo ".fa-anchor,.fa-coffee {font-size:200px}\n";
echo "</style>\n";
echo "<body>\n";
echo "\n";
echo "<!-- Navbar -->\n";
echo "<div class=\"w3-top\">\n";
echo "  <div class=\"w3-bar w3-red w3-card w3-left-align w3-large\">\n";
echo "	<a class=\"w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red\" href=\"javascript:void(0);\" onclick=\"myFunction()\" title=\"Toggle Navigation Menu\"><i class=\"fa fa-bars\"></i></a>\n";
echo "	<a href=\"/index.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">HOME</a>\n";
echo "	<a href=\"/fzsnes1.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZSNES1</a>\n";
echo "	<a href=\"/fzsnes2.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZSNES2</a>\n";
echo "	<a href=\"/fzmv.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZMV</a>\n";
echo "	<a href=\"/fzx.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZX</a>\n";
echo "	<a href=\"/fzxdd.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZXDD</a>\n";
echo "	<a href=\"/fzgpl.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZGPL</a>\n";
echo "	<a href=\"/fzcmx.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZCMX</a>\n";
echo "	<a href=\"/fzxcmx.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">FZXCMX</a>\n";
echo "	<a href=\"/smash1.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">SMASH64</a>\n";
echo "	<a href=\"/smash2.html\" class=\"w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white\">19XXG6</a>\n";
echo " </div>\n";
echo "\n";
echo "  <!-- Navbar on small screens -->\n";
echo "  <div id=\"navDemo\" class=\"w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large\">\n";
echo "    <a href=\"/index.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">HOME</a>\n";
echo "    <a href=\"/fzsnes1.html\" class=\"w3-bar-item w3-button w3-padding-large w3--white\">FZSNES1</a>\n";
echo "    <a href=\"/fzsnes2.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZSNES2</a>\n";
echo "    <a href=\"/fzmv.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZMV</a>\n";
echo "    <a href=\"/fzx.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZX</a>\n";
echo "    <a href=\"/fzxdd.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZXDD</a>\n";
echo "    <a href=\"/fzgpl.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZGPL</a>\n";
echo "    <a href=\"/fzcmx.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZCMX</a>\n";
echo "    <a href=\"/fzxcmx.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">FZXCMX</a>	\n";
echo "    <a href=\"/smash1.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">SMASH64</a>\n";
echo "    <a href=\"/smash2.html\" class=\"w3-bar-item w3-button w3-padding-large w3-white\">19XXG6</a>\n";
echo "  </div>\n";
echo "</div>\n";
echo "\n";
echo "<!-- First Grid -->\n";
echo "<div class=\"w3-row-padding w3-padding-64 w3-container\">\n";
echo "  <div class=\"w3-content\">\n";
echo "    <h1>F-ZERO ONLINE!</h1>\n";
echo "    <h5 class=\"w3-padding-32\">An emulation site pushing the limits of internet browsers. And, of course, your racing skills!</h5>\n";
echo "\n";
echo "    <p class=\"w3-text-grey\">It's F-Zero. A balls-hard, breakneck speed, futuristic anti gravity racing game published by Nintendo. Imagine: Racing at speeds above the sound barrier, having boost limited by your health bar, and the other pilots are actively trying to kill and destroy you.</p>\n";
echo "    <p class=\"w3-text-grey\">Also, as a bonus there is Smash64 and the romhack of the game 19XXG6!</p>\n";
echo "  </div>\n";
echo "</div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "<!-- Footer -->\n";
echo "<footer class=\"w3-container w3-padding-64 w3-center w3-opacity\">  \n";
echo " <p>Theme Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" target=\"_blank\">w3.css</a></p>\n";
echo " <p>Emulation Powered by <a href=\"http://neptunjs.xyz/\" target=\"_blank\">NeptunJS</a></p>\n";
echo "</footer>\n";
echo "\n";
echo "<script>\n";
echo "// Used to toggle the menu on small screens when clicking on the menu button\n";
echo "function myFunction() {\n";
echo "  var x = document.getElementById(\"navDemo\");\n";
echo "  if (x.className.indexOf(\"w3-show\") == -1) {\n";
echo "    x.className += \" w3-show\";\n";
echo "  } else { \n";
echo "    x.className = x.className.replace(\" w3-show\", \"\");\n";
echo "  }\n";
echo "}\n";
echo "</script>\n";
echo "\n";
echo "</body>\n";
echo "</html>\n";

?>
